### ISSUE TITLE
okta-awscli doesn't detect the expired credentials from  ~/.aws/credentials

### ISSUE THREAD

**Issue by cosmih** [okta-awscli/okta-awscli#155]
**Describe the bug**
okta-awscli doesn't detect the expired credentials from the awscli profile created previously (by okta-awscli) in ~/.aws/credentials

**Expected behavior**
the expired  credentials are detected and authentication logic started again

**To Reproduce**

the okta profile in ~/.okta-aws
> [account1-role1]
> base-url = xxxxx.okta.com
> username = <email_address>
> factor = OKTA
> role = arn:aws:iam::0123456789:role/developer
> profile = account1-role1
> app-link = https://xxxxxx.okta.com/home/amazon_aws/xxxxxxxx/272
> duration = 3600

perform a succesfull authentication
> okta-awscli --debug --okta-profile account1-role1
> DEBUG - Setting AWS role to arn:aws:iam::0123456789:role/developer
> DEBUG - Setting AWS partition to AwsPartition.AWS
> DEBUG - Setting AWS profile to account1-role1
> INFO - No existing credentials found. Requesting new credentials.
> DEBUG - Setting MFA factor to OKTA
> INFO - App Link set as: https://xxxxxx.okta.com/home/amazon_aws/xxxxxxxx/272
> INFO - Authenticating to: xxxxx.okta.com
> INFO - Authenticating as: <email_address>
> Enter password: 
> Multi-factor Authentication required for application.
> Pick a factor:
> [ 0 ] Okta Verify App: SmartPhone_IPhone: my_phone_name
> [ 1 ] token:software:totp( OKTA ) : <email_address>
> Selection: 0
> INFO - Okta Verify push sent...
> INFO - Using predefined role: arn:aws:iam::0123456789:role/developer
> INFO - Authenticating to: xxxxx.okta.com
> DEBUG - Requesting a duration of 3600 seconds
> DEBUG - Getting STS token against ARN partition: AwsPartition.AWS
> INFO - Session token expires on: 2021-02-04 17:03:07+00:00
> INFO - Temporary credentials written to profile: account1-role1
> INFO - Invoke using: aws --profile account1-role1 <service> <command>

the awscli profile in ~/.aws/credentials
> [account1-role1]
> aws_access_key_id = access key
> aws_secret_access_key = secret key
> aws_session_token = session token

check the access with awscli
> aws --profile account1-role1 sts get-caller-identity
> {
>     "UserId": "AROA3YKYIKGJUZMWZFVD2:<email_address>,
>     "Account": "0123456789",
>     "Arn": "arn:aws:sts::0123456789:assumed-role/developer/<email_address>"
> }

continue the work until the credentials expire (1 hour)

the awscli complains about the credentials being xpired
> aws --profile account1-role1 sts get-caller-identity
> An error occurred (ExpiredToken) when calling the GetCallerIdentity operation: The security token included in the request is expired

have okta-awscli executed again
> okta-awscli --debug --okta-profile account1-role1 
> DEBUG - Setting AWS role to arn:aws:iam::0123456789:role/aws_admin
> DEBUG - Setting AWS partition to AwsPartition.AWS
> DEBUG - Setting AWS profile to account1-role1
> DEBUG - Checking STS token against ARN partition: AwsPartition.AWS
> INFO - STS credentials are valid. Nothing to do.

**Environment (please complete the following information):**
- MacOS 11.2
> uname -a
> Darwin LT-PARKM-317 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
- okta-awscli 0.4.6
> okta-awscli --version
> 0.4.6
- awscli 2.1.22
> aws --version
> aws-cli/2.1.22 Python/3.7.4 Darwin/20.3.0 exe/x86_64 prompt/off
- python 3.9.1
> python3 -V
> Python 3.9.1

**Additional context**
If I delete the awscli profile from ~/.aws/credentials and I run okta-awscli again it works but it not friendly at all when you have 10+ profile to deal with

**Comment by cosmih** [comment]
testing the same awscli profile using the below code it throws the expected error
> cat > sts.py <<EOF
> import boto3
> session = boto3.Session(profile_name="account1-role1")
> sts = session.client("sts")
> sts.get_caller_identity()
> EOF
>
> python3 sts.py
> Traceback (most recent call last):
>  File "/Users/cosmih/sts.py", line 4, in <module>
>    sts.get_caller_identity()
>  File "/Users/cosmih/Library/Python/3.9/lib/python/site-packages/botocore/client.py", line 337, in _api_call
>    return self._make_api_call(operation_name, kwargs)
>  File "/Users/cosmih/Library/Python/3.9/lib/python/site-packages/botocore/client.py", line 656, in _make_api_call
>    raise error_class(parsed_response, operation_name)
> botocore.exceptions.ClientError: An error occurred (ExpiredToken) when calling the GetCallerIdentity operation: The security token included in the request is expired

**Comment by cosmih** [comment]
I've tested with similar same logic as in aws_auth.py and the same expected error is returned

> import os
> import sys
> import boto3
> from configparser import RawConfigParser
> 
> profile = "account1-role1"
> home_dir = os.path.expanduser('~')
> creds_file = home_dir + "/.aws/credentials"
>
> parser = RawConfigParser()
> parser.read(creds_file)
>
> if not parser.has_section(profile):
>     sys.exit(1)
>
> session = boto3.Session(profile_name=profile)
> sts = session.client("sts")
> sts.get_caller_identity()

**Comment by cosmih** [comment]
I've did some more troubleshooting and okta_awscli.py is not getting the awscli profile from ~/.okta-aws
It works when using `--profile` as below
> okta-awscli --okta-profile account1-role1 --profile account1-role1

It doesn't work when expecting the awscli profile to be fetch from okta profile , meaning as below
> okta-awscli --okta-profile account1-role1

where okta profile looks like
> [account1-role1]
> base-url = xxxxx.okta.com
> username = <email_address>
> factor = OKTA
> role = arn:aws:iam::0123456789:role/developer
> profile = account1-role1
> app-link = https://xxxxxx.okta.com/home/amazon_aws/xxxxxxxx/272
> duration = 3600

**Comment by cosmih** [comment]
My quick and dirty workaround is as below:

- additional code into `OktaAuthConfig` class

```
    def profile_for(self, okta_profile):
        """ Gets profile from config """
        if self._value.has_option(okta_profile, 'profile'):
            profile = self._value.get(okta_profile, 'profile')
            self.logger.debug("Setting profile to %s" % profile)
            return profile
        return None
```

- additional code into the `main` function from `okta_awscli.py`

```
    if not okta_profile:
        okta_profile = "default"

    if not profile:
        okta_auth_config = OktaAuthConfig(logger)
        profile = okta_auth_config.profile_for(okta_profile):

```

**Comment by cosmih** [comment]
My use case as below:

1. use the okta-awscli to create or update if already exists the awscli profile with temporary credentials
2. use the awscli profile for and other tool/program relyin on it (awscli, aws-sam-cli, Visual Studio Code, GUI tools dealing with S3, terraform, etc)

**Comment by cybercussion** [comment]
I'm on a M1 Mac, it doesn't seem to read or write to the ~/.aws/credentials.  I don't know if its SIP or something else.  Maybe I'll delete the credentials file and see if that fixes it
