### ISSUE TITLE
ERROR - Authentication failed

### ISSUE THREAD

**Issue by johnjelinek** [okta-awscli/okta-awscli#178]
**Describe the bug**
I used the password from my password manager. Are there any characters that are not allowed with the password? Should the username include the domain or not?

**To Reproduce**
* Set up ~/.okta-aws
* `okta-awscli -d`

**Expected behavior**
I expected to be logged in.

**Output**
```
okta-awscli -d
DEBUG - Setting AWS role to arn:aws:iam::[redacted]:role/[redacted]
DEBUG - Setting AWS partition to AwsPartition.AWS
DEBUG - Setting AWS profile to default
INFO - No existing credentials found. Requesting new credentials.
DEBUG - Setting MFA factor to OKTA
INFO - App Link set as: https://[redacted].okta.com/home/amazon_aws/[redacted]
INFO - Authenticating to: [redacted].okta.com
INFO - Authenticating as: "[redacted]"
ERROR - Authentication failed
```

**Environment (please complete the following information):**
 - OS: MacOS 11.6
 - Version of okta-awscli you're running: `0.5.0`

**Additional context**
Using the pip3 that comes with MacOS.

**Comment by imki123** [comment]
When I use spacial character '$' in password, it did not work. Thank you @johnjelinek !

**Comment by johnfreund** [comment]
I'm having this issue after updating to 0.5.0 (I unfortunately don't recall what my prior version was).   Exact debug output as op.

**Comment by maxtacu** [comment]
I will close the issue due to outdated data and new releases since the the last comment. Please feel free to reopen it or create a new one in case you have any similar/new issues with the latest `0.5.4` version.
