### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by maxtacu** [okta-awscli/okta-awscli#184]
Hey @jmhale thank you for this great project! I just have a question - is it still alive? I recently pushed my changes and created a pull request [#183], but I see that there are a lot of issues and other stale pull requests which are not merged or commented for ~6 months or more. I am actively using this tool and would like to continue maintaining it, but I would not like to have my PRs merged or issues reviewed in 6+ months

**Comment by ricktbaker** [comment]
Interested in knowing the same.  Considering using this as we are making the switch to okta, but only if this isn't a dead project.

**Comment by jmhale** [comment]
Hey @maxtacu and @ricktbaker thanks for reaching out about the project and giving me a chance to respond.

While this project isn't dead and I'd certainly like to keep it going, it's become a bit unwieldy to adequately test the changes submitted and get them deployed in a timely manner, when weighed against all of the other demands on my time these days. 

I've made a couple of unsuccessful attempts at devising a testing scheme to try and automate some of that, but as it stands today, for each of the PRs, I need to test them against a live Okta test tenant across a bunch of scenarios to make sure we're not introducing regressions. All of that makes it easy for me to get backlogged if I'm not staying on top of it (hint: I'm really bad at that).

All of that said, I'm open if folks are interested in jumping in as maintainers. I want to stay involved in the project, but I'm sure that there are smarter ways to be doing some of these things and if people want to get involved more, I'm all for it.

If there's interest, I can move this repo over to its own org and we can get folks added as contributors.

**Comment by maxtacu** [comment]
Hey @jmhale, thanks for your reply. Totally understand you. I'm also full time employed and plan to contribute in my free time, but I believe that with overall community support we can continue development of this project. That's what open-source is about. We just want to help you with this project to avoid bottlenecks and advance the development. 
One way which you already described is creating an org and move it there, but there might be also another way where you can just add members to the existing public repo with proper permissions. Any of these will work. Just to keep ball rolling 😉

**Comment by maxtacu** [comment]
@jmhale any update on this?

**Comment by jmhale** [comment]
@maxtacu Yup, I created the org a few days ago and then immediately got distracted by something shiny. I just transferred this repo over to the new org and invited you to it.

**Comment by maxtacu** [comment]
Thanks @jmhale! Can you please also grant me permissions to review and merge changes? also we need to update the README of this project mentioning that it is migrated to a new location and support will continue there.

**Comment by jmhale** [comment]
@maxtacu Just added you to the maintainers group, which should give you the access you need. lmk if something isn't right still.

**Comment by sadok-f** [comment]
we're using `okta-awscli` heavily, happy to see it continue to be alive 🥳
