### ISSUE TITLE
okta-awscli duplicates the config file when appending to it

### ISSUE THREAD

**Issue by tdmalone** [okta-awscli/okta-awscli#199]
**Describe the bug**
When `~/.okta-aws` already exists and `okta-awscli --config` is run, it results in the entire existing contents of the config file being appended. It likely needs to either append only the new profile, OR instead of appending, replace the old contents with the new contents, rather than attempting to do both.

**To Reproduce**
1. With an existing profile already in place, run `okta-awscli --config`
2. Enter `y` when prompted, to proceed to append the new profile
3. Answer the questions as necessary
4. The command succeeds, but when trying to use `okta-awscli`, an error will be received due to duplicate profiles

**Expected behavior**
The new profile to append, rather than the existing contents of the file also being appended.

**Output**

**Environment (please complete the following information):**
 - OS: macOS
 - Version of okta-awscli: 0.5.4

**Additional context**

**Comment by jwflynn** [comment]
I see the same behavior in windows
