### ISSUE TITLE
Contributing back our internal changes

### ISSUE THREAD

**Issue by kholia** [okta-awscli/okta-awscli#220]
Hey - This is Dhiru here.

We have been using an internal fork of https://github.com/okta-awscli/okta-awscli @ Work and it is working well for us.

I am wondering if we could contribute back our changes to the this (upstream) repository.

Some of our internal fork changes include:

- Support for FIDO2 YubiKey(s)
- Support for Touch ID on macOS

Thanks for your time, and attention.

Cheers!

**Comment by maxtacu** [comment]
feel free to contribute. review process is quite slow sometimes due to overload at work and family (kids), but we will do our best
